universe                = docker
docker_image            = pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime
executable              = execute.sh
arguments               = test.py
output                  = edge_connect.pth
error                   = out.err
log                     = out.log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1